# Generated by Django 5.0.3 on 2024-03-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='remark',
            new_name='remarks',
        ),
    ]
